export { default as Admin } from './Admin/Admin';
export { default as BookingsManagment } from './Admin/components/BookingsManagment';
export { default as RoomsManagment } from './Admin/components/RoomsManagment';
export { default as SideBar } from './Admin/components/SideBar';
export { default as UserManagment } from './Admin/components/UserManagment';
export { default as Auth } from './Auth/Auth';
export { default as AuthForm } from './Auth/components/AuthForm/AuthForm';
export { default as Home } from './Home/Home';
//export * from './Home/components';
export { default as PageNotFound } from './PageNotFound/PageNotFound';
